const plants = [
  {id:'04', type:'strawberry', stage:'FLOWERING', health:92, ph:'5.9', ec:'1.8', temp:'21.4°C', age:'34 days'},
  {id:'07', type:'strawberry', stage:'FRUITING', health:88, ph:'5.9', ec:'1.8', temp:'21.4°C', age:'41 days'},
  {id:'02', type:'strawberry', stage:'VEGETATIVE', health:96, ph:'6.0', ec:'1.7', temp:'21.1°C', age:'28 days'}
];
const nft = document.querySelector('#nftSlots'), dwc = document.querySelector('#dwcSlots');
function fillSlots(el, count, emptyIndexes=[]){for(let i=0;i<count;i++){const slot=document.createElement('button');slot.className='plant-slot '+(emptyIndexes.includes(i)?'empty':'');slot.textContent=emptyIndexes.includes(i)?'·':'✿';slot.dataset.plant=i%3===0?'04':i%3===1?'07':'02';slot.title=emptyIndexes.includes(i)?'Empty slot':`Strawberry #${slot.dataset.plant}`;if(!emptyIndexes.includes(i))slot.addEventListener('click',()=>openPlant(slot.dataset.plant));el.append(slot)}}
fillSlots(nft,18,[5,11,16]); fillSlots(dwc,12,[2,8]);
function openPlant(id){const p=plants.find(x=>x.id===id)||plants[0];showDialog(`<div class="detail-content"><div class="subtitle">PLANT STATUS WINDOW</div><h2>✿ STRAWBERRY #${p.id}</h2><div class="subtitle">${p.stage} · ${p.age}</div><div class="detail-grid"><div class="detail-stat"><small>HEALTH</small><strong style="color:var(--green)">${p.health}% ✓</strong></div><div class="detail-stat"><small>EXPECTED HARVEST</small><strong>~ 17 days</strong></div><div class="detail-stat"><small>PH</small><strong>${p.ph} ✓</strong></div><div class="detail-stat"><small>EC</small><strong>${p.ec} ✓</strong></div><div class="detail-stat"><small>ROOT TEMP</small><strong>${p.temp} ✓</strong></div><div class="detail-stat"><small>LOCATION</small><strong>NFT A · SLOT 04</strong></div></div><div class="detail-actions"><button class="pixel-action" data-toast="Growth note opened">＋ ADD NOTE</button><button class="pixel-action" data-toast="Harvest form opened">RECORD HARVEST</button><button class="pixel-action" data-toast="Problem report opened">REPORT PROBLEM</button></div></div>`)}
function showDialog(html){document.querySelector('#dialogContent').innerHTML=html;document.querySelector('#detailDialog').showModal();document.querySelectorAll('[data-toast]').forEach(b=>b.onclick=()=>{showToast(b.dataset.toast);document.querySelector('#detailDialog').close()})}
document.querySelectorAll('[data-entity]').forEach(b=>b.addEventListener('click',()=>{const type=b.dataset.entity;if(type==='reservoir')showDialog(`<div class="detail-content"><div class="subtitle">HYDRO SYSTEM OBJECT</div><h2>▣ RESERVOIR A</h2><div class="subtitle">ACTIVE · 420 / 510 L</div><div class="detail-grid"><div class="detail-stat"><small>WATER LEVEL</small><strong style="color:var(--aqua)">82% ✓</strong></div><div class="detail-stat"><small>PH RANGE</small><strong>5.5—6.2</strong></div><div class="detail-stat"><small>EC RANGE</small><strong>1.5—2.2</strong></div><div class="detail-stat"><small>LAST WATER CHANGE</small><strong>2 days ago</strong></div></div><div class="detail-actions"><button class="pixel-action" data-toast="Water change form opened">RECORD WATER CHANGE</button><button class="pixel-action" data-toast="Nutrient dose form opened">ADD NUTRIENTS</button></div></div>`); else showToast(`${type.toUpperCase()} selected`)}));
document.querySelector('#closeDialog').onclick=()=>document.querySelector('#detailDialog').close();
document.querySelector('#detailDialog').addEventListener('click',e=>{if(e.target.id==='detailDialog')e.target.close()});
function showToast(message){const t=document.querySelector('#toast');t.textContent='✦ '+message;t.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove('show'),2400)}
document.querySelectorAll('.quest input').forEach(input=>input.addEventListener('change',()=>{input.closest('.quest').classList.toggle('done',input.checked);showToast(input.checked?'Quest complete · +10 FARM XP':'Quest reopened')}));
document.querySelectorAll('.nav-item').forEach(n=>n.addEventListener('click',()=>{document.querySelectorAll('.nav-item').forEach(x=>x.classList.remove('active'));n.classList.add('active');if(n.dataset.nav!=='MAP')showToast(`${n.dataset.nav} screen queued for next build`)}));
document.querySelectorAll('.mini-button').forEach(n=>n.addEventListener('click',()=>{document.querySelectorAll('.mini-button').forEach(x=>x.classList.remove('active'));n.classList.add('active');showToast(`${n.textContent} view selected`)}));
function tick(){const d=new Date();document.querySelector('#clock').textContent=d.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false})}tick();setInterval(tick,1000);
